name = "unicornwars"
type = "javascript"
account_id = "bd9cea6f3f923ec196e07ad67ba78f88"
workers_dev = true
route = ""
zone_id = "ffdb94f661065101e83181fe7b0d7f7f"
kv_namespaces = [ 
         { binding = "SCOREBOARD", id = "SCOREBOARD", preview_id = "0b54996dd6904fca989818883ab11d62", deploy_id = "d71bf2d0786d4c8aba9fd3c1f915bd86"}
]

[site]
bucket = "./public"
